package su.nightexpress.nexshop.shop.chest.editor;

public enum ChestEditorType {

    SHOP_CHANGE_NAME,
    SHOP_CHANGE_TYPE,
    SHOP_CHANGE_TRANSACTIONS,
    SHOP_CHANGE_PRODUCTS,
    SHOP_BANK,
    SHOP_BANK_DEPOSIT,
    SHOP_BANK_WITHDRAW,
    SHOP_DELETE,

    //PRODUCT_CHANGE_COMMANDS,
    PRODUCT_CHANGE_CURRENCY,

    PRODUCT_CHANGE_PRICE_BUY,
    PRODUCT_CHANGE_PRICE_BUY_MIN,
    PRODUCT_CHANGE_PRICE_BUY_MAX,
    PRODUCT_CHANGE_PRICE_SELL,
    PRODUCT_CHANGE_PRICE_SELL_MIN,
    PRODUCT_CHANGE_PRICE_SELL_MAX,

    PRODUCT_CHANGE_PRICE_RANDOMIZER_TOGGLE,
    PRODUCT_CHANGE_PRICE_RANDOMIZER_TIMES,
    PRODUCT_CHANGE_PRICE_RANDOMIZER_TIMES_DAY,
    PRODUCT_CHANGE_PRICE_RANDOMIZER_TIMES_TIME,
}
