package su.nightexpress.nexshop.shop.virtual.editor;

public enum VirtualEditorType {

    SHOP_CHANGE_TITLE,
    SHOP_CHANGE_PAGES,
    SHOP_CHANGE_ICON,
    SHOP_CHANGE_DISCOUNTS,
    SHOP_CHANGE_PRODUCTS,
    SHOP_CHANGE_PERMISSION,
    SHOP_CHANGE_TRANSACTIONS,
    SHOP_CHANGE_CITIZENS_ID,
    SHOP_CHANGE_VIEW_DESIGN,
    SHOP_CREATE,
    SHOP_DELETE,

    DISCOUNT_CREATE,
    DISCOUNT_CHANGE_DISCOUNT,
    DISCOUNT_CHANGE_DAY,
    DISCOUNT_CHANGE_TIME,

    PRODUCT_CHANGE_PREVIEW,
    PRODUCT_CHANGE_ITEM,
    PRODUCT_CHANGE_COMMANDS,
    PRODUCT_CHANGE_DISCOUNT,
    PRODUCT_CHANGE_ITEM_META,
    PRODUCT_CHANGE_CURRENCY,

    PRODUCT_CHANGE_PRICE_BUY,
    PRODUCT_CHANGE_PRICE_BUY_MIN,
    PRODUCT_CHANGE_PRICE_BUY_MAX,
    PRODUCT_CHANGE_PRICE_SELL,
    PRODUCT_CHANGE_PRICE_SELL_MIN,
    PRODUCT_CHANGE_PRICE_SELL_MAX,

    PRODUCT_CHANGE_LIMIT,
    PRODUCT_CHANGE_LIMIT_BUY_AMOUNT,
    PRODUCT_CHANGE_LIMIT_BUY_RESET,
    PRODUCT_CHANGE_LIMIT_SELL_AMOUNT,
    PRODUCT_CHANGE_LIMIT_SELL_RESET,

    PRODUCT_CHANGE_PRICE_RANDOMIZER_TOGGLE,
    PRODUCT_CHANGE_PRICE_RANDOMIZER_TIMES,
    PRODUCT_CHANGE_PRICE_RANDOMIZER_TIMES_DAY,
    PRODUCT_CHANGE_PRICE_RANDOMIZER_TIMES_TIME,
}
